apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-cuda-11.6
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/weiliu/ubuntu-cuda-11.6:latest
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /mnt/data
      name: data-vol
    command: ["sleep", "infinity"]
    securityContext:
      privileged: false
    resources:
      limits:
        memory: 16Gi
        nvidia.com/gpu: 1
      requests:
        memory: 16Gi
        nvidia.com/gpu: 1
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 1024Mi
    - name: data-vol
      persistentVolumeClaim:
        claimName: data-pvc
  imagePullSecrets:
  - name: regcredw
  spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090