apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-cuda
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/weiliu/ubuntu-cuda-11.4:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 16Gi
        nvidia.com/gpu: 2
      requests:
        memory: 16Gi
        nvidia.com/gpu: 2
  imagePullSecrets:
  - name: regcredw
  spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In
            values:
            - 1080Ti