apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casper-tools-vol
spec:
  storageClassName: rook-ceph-block-pacific
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi