apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-cuda-11.4
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/weiliu/ubuntu-cuda-11.4:latest
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
    resources:
      limits:
        memory: 16Gi
        nvidia.com/gpu: 1
      requests:
        memory: 16Gi
        nvidia.com/gpu: 1
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 1024Mi
  imagePullSecrets:
  - name: regcredw
  spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In
            values:
            - 1080Ti