apiVersion: v1
kind: Pod
metadata:
  name: gpu-cuda-11-4
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:11.4.0-devel-ubuntu20.04
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
  spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In
            values:
            - 1080Ti

